name: Python test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: For set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Pip
        run: pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Test application
        run: pytest lab3_calc_3.py
