name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      #- name: Install dependencies
       # run: |
       #  run: python -m pip install --upgrade pip setuptools wheel
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
      - name: Test with pytest
        run: |
         pip install pytest pytest-cov
         pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      #- name: Display Python version
      #  run: python -c "import sys; print(sys.version)"
      
